sudo: required
services:
  - docker

before_install:
  - docker build -t pushpakr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pushpakr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "docker-react"
  env: "DockerReact-env"
  buket_name: "elasticbeanstalk-us-east-1-434129921189"
  bucket_path: "docker-react"
  on:
   branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"
